version: 2.1
orbs:
  node: circleci/node@5

jobs:
  dependencies_install:
    executor: node/default
    steps:
      - checkout
      # Installing project dependencies
      - run: echo "installing dependencies"

  code_analysing:
    executor: node/default
    steps:
      - checkout
      # Running code analysis
      - run: echo "code analyzing ..."

  cleaning_packaging:
    executor: node/default
    steps:
      - checkout
      # Cleaning and packaging the code
      - run: echo "cleaning and packaging ..."

  unit_tests:
    executor: node/default
    steps:
      - checkout
      # Running unit tests
      - run: echo "unit tests"

  integration_tests:
    executor: node/default
    steps:
      - checkout
      # Running integration tests
      - run: echo "integration tests"

  regression_tests:
    executor: node/default
    steps:
      - checkout
      # Running regression tests
      - run: echo "regression tests"

  performance_tests:
    executor: node/default
    steps:
      - checkout
      # Running performance tests
      - run: echo "performance tests"

  security_tests:
    executor: node/default
    steps:
      - checkout
      # Running security tests
      - run: echo "security tests"

  access_tests:
    executor: node/default
    steps:
      - checkout
      # Running access tests
      - run: echo "access tests"

  preparing_deploying_environment:
    executor: node/default
    steps:
      - checkout
      # Preparing the deployment environment
      - run: echo "preparation of deploying environment"

  application_deployement:
    executor: node/default
    steps:
      - checkout
      # Deploying the application
      - run: echo "application deployment"

  verification_tests:
    executor: node/default
    steps:
      - checkout
      # Running verification tests
      - run: echo "verification tests"

  functionning_validation_tests:
    executor: node/default
    steps:
      - checkout
      # Running functioning validation tests
      - run: echo "functioning validation tests"

  charge_tests:
    executor: node/default
    steps:
      - checkout
      # Running charge tests
      - run: echo "charge tests"

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      # Deploying to development environment
      - run: echo "Deploying to development environment"

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      # Deploying to production environment
      - run: echo "Deploying to production environment"

  monitoring:
    executor: node/default
    steps:
      - checkout
      # Monitoring the application
      - run: echo "monitoring"

###################################################################
workflows:
  build-test-deploy:
    jobs:
      - dependencies_install
      - code_analysing
      - cleaning_packaging
      ##############
      - unit_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - integration_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - regression_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - performance_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - security_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging

      - access_tests:
          requires:
            - dependencies_install
            - code_analysing
            - cleaning_packaging
          filters:
            branches:
              only:
                - master
      ###############
      - preparing_deploying_environment:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - application_deployement:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - verification_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - functionning_validation_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - charge_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/

      - deploy_dev:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              only:
                - develop

      - deploy_prod:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              only:
                - master

      - monitoring:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /feature\/\/*/
                - /hotfix\/\/*/
