version: 2.1

# Orbs declaration
orbs:
  node: circleci/node@5

# Job definitions
jobs:
  # Job to install project dependencies
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing project dependencies..."

  # Job to analyze the project's code
  code_analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Performing code analysis..."

  # Job to clean and package the project
  clean_package:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and packaging the project..."

  # Job to run unit tests
  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running unit tests..."

  # Job to run integration tests
  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."

  # Job to run regression tests
  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."

  # Job to run performance tests
  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."

  # Job to run security tests
  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."

  # Job to run access tests
  access_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running access tests..."

  # Job to prepare the deployment environment
  prepare_deploy_env:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing deployment environment..."

  # Job to deploy the application
  deploy_application:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying the application..."

  # Job to perform verification tests
  verify_deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "Performing verification tests..."

  # Job to validate the functioning of the deployed application
  validate_functioning:
    executor: node/default
    steps:
      - checkout
      - run: echo "Validating the functioning of the deployed application..."

  # Job to perform charge tests
  charge_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Performing charge tests..."

  # Job to deploy to development environment
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  # Job to deploy to production environment
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

  # Job to deploy to release environment
  deploy_release:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to release environment..."

  # Job for monitoring
  monitoring:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring..."

# Workflow definition
workflows:
  build-test-deploy:
    jobs:
      # Stage 1: Install dependencies, code analysis, and clean package
      - install_dependencies
      - code_analysis
      - clean_package

      # Stage 2: Run unit tests, integration tests, regression tests, performance tests, security tests, and access tests
      - unit_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
      - integration_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - regression_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - performance_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - security_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
      - access_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_package
          filters:
            branches:
              only:
                - master

      # Stage 3: Prepare deployment environment, deploy application, verify deployment, validate functioning, charge tests, and deployment to different environments
      - prepare_deploy_env:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - deploy_application:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - verify_deploy:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - validate_functioning:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - charge_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      - deploy_dev:
          requires:
            - prepare_deploy_env
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - prepare_deploy_env
          filters:
            branches:
              only:
                - master
      - deploy_release:
          requires:
            - prepare_deploy_env
          filters:
            branches:
              only:
                - /^release\/.*$/
      - monitoring:
          requires:
            - prepare_deploy_env
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
