# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."